import express from'express';import cors from'cors';import dotenv from'dotenv';import bcrypt from'bcryptjs';import jwt from'jsonwebtoken';import fs from'fs';import path from'path';import crypto from'crypto';
dotenv.config();const app=express();app.use(cors());app.use(express.json());const PORT=Number(process.env.PORT||5000);const SECRET=process.env.JWT_SECRET||'dev-secret';const dataDir=path.join(process.cwd(),'data');const file=path.join(dataDir,'hireflow.json');
type DB={users:any[];jobs:any[];candidates:any[]};function db():DB{if(!fs.existsSync(dataDir))fs.mkdirSync(dataDir,{recursive:true});if(!fs.existsSync(file))fs.writeFileSync(file,JSON.stringify({users:[],jobs:[],candidates:[]},null,2));return JSON.parse(fs.readFileSync(file,'utf8'))}function save(d:DB){fs.writeFileSync(file,JSON.stringify(d,null,2))}const id=()=>crypto.randomUUID();
function auth(req:any,res:any,next:any){const t=req.headers.authorization?.split(' ')[1];if(!t)return res.status(401).json({message:'Authentication required'});try{req.user=jwt.verify(t,SECRET);next()}catch{return res.status(401).json({message:'Invalid or expired session'})}}
app.get('/api/health',(_,r)=>r.json({ok:true}));
app.post('/api/auth/register',async(req,res)=>{const{name,email,password}=req.body;if(!name||!email||!password||password.length<6)return res.status(400).json({message:'Name, valid email and 6+ character password required'});const d=db();if(d.users.some(u=>u.email.toLowerCase()===email.toLowerCase()))return res.status(409).json({message:'Email already registered'});const user={id:id(),name:name.trim(),email:email.toLowerCase(),password:await bcrypt.hash(password,10),createdAt:new Date().toISOString()};d.users.push(user);save(d);const token=jwt.sign({id:user.id,email:user.email},SECRET,{expiresIn:'7d'});res.status(201).json({token,user:{id:user.id,name:user.name,email:user.email}})});
app.post('/api/auth/login',async(req,res)=>{const{email,password}=req.body;const d=db();const u=d.users.find(x=>x.email.toLowerCase()===String(email).toLowerCase());if(!u||!await bcrypt.compare(password,u.password))return res.status(401).json({message:'Invalid email or password'});const token=jwt.sign({id:u.id,email:u.email},SECRET,{expiresIn:'7d'});res.json({token,user:{id:u.id,name:u.name,email:u.email}})});
app.get('/api/dashboard',auth,(req:any,res)=>{const d=db(),uid=req.user.id,j=d.jobs.filter(x=>x.ownerId===uid),c=d.candidates.filter(x=>x.ownerId===uid);res.json({openJobs:j.filter(x=>x.status==='Open').length,totalCandidates:c.length,interviews:c.filter(x=>x.stage==='Interview').length,hired:c.filter(x=>x.stage==='Hired').length,recent:c.sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,5)})});
app.get('/api/jobs',auth,(req:any,res)=>res.json(db().jobs.filter(x=>x.ownerId===req.user.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))));
app.post('/api/jobs',auth,(req:any,res)=>{if(!req.body.title)return res.status(400).json({message:'Job title required'});const d=db(),j={id:id(),...req.body,ownerId:req.user.id,createdAt:new Date().toISOString()};d.jobs.push(j);save(d);res.status(201).json(j)});
app.put('/api/jobs/:id',auth,(req:any,res)=>{const d=db(),i=d.jobs.findIndex(x=>x.id===req.params.id&&x.ownerId===req.user.id);if(i<0)return res.status(404).json({message:'Job not found'});d.jobs[i]={...d.jobs[i],...req.body,id:d.jobs[i].id,ownerId:req.user.id};save(d);res.json(d.jobs[i])});
app.delete('/api/jobs/:id',auth,(req:any,res)=>{const d=db(),before=d.jobs.length;d.jobs=d.jobs.filter(x=>!(x.id===req.params.id&&x.ownerId===req.user.id));if(d.jobs.length===before)return res.status(404).json({message:'Job not found'});d.candidates=d.candidates.map(c=>c.jobId===req.params.id?{...c,jobId:''}:c);save(d);res.status(204).end()});
app.get('/api/candidates',auth,(req:any,res)=>res.json(db().candidates.filter(x=>x.ownerId===req.user.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))));
app.post('/api/candidates',auth,(req:any,res)=>{if(!req.body.name||!req.body.email||!req.body.role)return res.status(400).json({message:'Name, email and role required'});const d=db(),c={id:id(),...req.body,ownerId:req.user.id,stage:req.body.stage||'Applied',createdAt:new Date().toISOString()};d.candidates.push(c);save(d);res.status(201).json(c)});
app.put('/api/candidates/:id',auth,(req:any,res)=>{const d=db(),i=d.candidates.findIndex(x=>x.id===req.params.id&&x.ownerId===req.user.id);if(i<0)return res.status(404).json({message:'Candidate not found'});d.candidates[i]={...d.candidates[i],...req.body,id:d.candidates[i].id,ownerId:req.user.id};save(d);res.json(d.candidates[i])});
app.patch('/api/candidates/:id/stage',auth,(req:any,res)=>{const allowed=['Applied','Screening','Interview','Offered','Hired','Rejected'];if(!allowed.includes(req.body.stage))return res.status(400).json({message:'Invalid stage'});const d=db(),c=d.candidates.find(x=>x.id===req.params.id&&x.ownerId===req.user.id);if(!c)return res.status(404).json({message:'Candidate not found'});c.stage=req.body.stage;save(d);res.json(c)});
app.delete('/api/candidates/:id',auth,(req:any,res)=>{const d=db(),before=d.candidates.length;d.candidates=d.candidates.filter(x=>!(x.id===req.params.id&&x.ownerId===req.user.id));if(d.candidates.length===before)return res.status(404).json({message:'Candidate not found'});save(d);res.status(204).end()});
app.use((_, res) =>
  res.status(404).json({ message: 'Route not found' })
);

if (process.env.NODE_ENV !== 'production') {
  app.listen(PORT, () =>
    console.log(`HireFlow API running on http://localhost:${PORT}`)
  );
}

export default app;